
* Features, fixes

  - 'show appt date in calendar' button in the article buffer, to see whether
    there are already conflicting events in the calendar

  - wrap calendar description lines in the article buffer

  - In Gnus I can't see that I have Accepted/Tentative'd/Declined an
    invitation. This would be nice to display - maybe by adding a custom
    header? Also the A'nswered mark could be set?

    Not sure about the headers and summary buffer. But as long as the
    information is kept in the org entry, it is possible to show this in the
    article buffer.

  - My colleague then canceled the meeting, but the cancel notification
    was shown with "Accept"-, "Tentative"-, and "Decline"-buttons, rather
    than the "Remove from calendar"-button (or no button) I expected.

  - Maybe add menu items and keyboard shortcuts for Accept, Tentative,
    Decline?

  - maybe allow syncing (actually creation of new org entry) from REPLY
    events. When I send a meeting request from owa, I have no record of it in
    org yet. If not feasible, don't show sync buttons for replies.
